name 'apache'
maintainer 'Sudheer'
maintainer_email 'Sudheer.sk3@gmail.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.2.1'
